### ISSUE TITLE
Click event handling

### ISSUE THREAD

**Issue by tfwright** [nylen/shiftcheckbox#3]
Thanks for a very useful plugin.

I have a slight problem with links/buttons in a table row I want to make clickable.  For those, I don't want the checkbox state to be changed.  From the docs:

> Note that if a row contains clickable elements such as links or buttons, they should have a click handler which returns false if you do not want the clicks to be passed through to the checkboxes

The problem with this is returning false in a click handler on the links/buttons themselves breaks their behavior as well as stops the checkbox change.  It seems like the 'proper' way to handle that would be to support an option in the plugin to ignore certain dom elements clicks.  Just looking through the code quickly, it looks like all that's needed is a condition [here](https://github.com/nylen/shiftcheckbox/blob/gh-pages/jquery.shiftcheckbox.js#L156-L157).

Thoughts?

**Comment by nylen** [comment]
Maybe that would be a simple change.  I have a hard time reasoning about this code because there are so many edge cases.  It really needs some tests (#2).

I'd accept a PR for this.  What I've done in the past though is just recreate the action of the link or button in its event handler, then return false:

``` js
// For a link
$('#checkboxes a').click(function() {
    window.location.href = $(this).attr('href');
    return false;
});

// For a form submit button
$('#checkboxes input[type=submit]').click(function() {
    $(this).closest('form').submit();
    return false;
});
```

**Comment by tfwright** [comment]
Hey @nylen, let me know what you think when you get a minute to check out that PR.  Quick QA seemed to work fine for me w/o breaking any features.  But I'll probably be using my branch in a prod app soon if you want to wait on some more intensive testing...
