### ISSUE TITLE
onChange bug?

### ISSUE THREAD

**Issue by DanielFurmanov** [nylen/shiftcheckbox#5]
Hi, there! 
First of all thanks for the plugin, its really useful, but recently I`ve encountered this case:

I have a table with checkbox in the end of every row, by this code i highlight the last td if checkbox was changed
`$(document).on('change', 'input[type="checkbox"]', function() {
    $(this).toggleBackgroundColorByTag('blah-blah-parameters');
});`
And then I saw that change triggers only for those checkboxes which I actually click (first and last one of shiftcheckbox chain), I thought that this is strange, but then I realized that this could be intentional

so I modified  my shiftcheckbox options with this property
`onChange: function() {
    this.trigger('change');
}`
**_BUT**_ now when I click with shift checkboxes it triggers 'change' n+1 time (if I have 10 checkboxes selected than 11 'onChange' will be triggered).
Is it a bug? Or did I do something wrong? What should I do if I want exactly the same quantity of 'change' triggered as checkboxes I actually selected?

**Comment by nylen** [comment]
> so I modified my shiftcheckbox options with this property
> `onChange: function() { this.trigger('change'); }`

I'm surprised this doesn't cause an infinite loop.

Try something like this instead, it seems to work well: http://jsfiddle.net/1n7ujs98/
